trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install --force
    ng build
  displayName: 'npm install and build'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: Vm
    sourceFolder: dist/mnext-calc
    contents: '**'
    targetFolder: /home/beheerder/energiecoach2/public   
    cleanTargetFolder: true 
